services:
  feedforward:
    build: .
    container_name: feedforward-app
    networks:
      - feedforward-net
    expose:
      - "5001"  # Only expose internally to the network
    volumes:
      # Persist data directory
      - feedforward-data:/app/data
      # Mount production .env file
      - ./.env.production:/app/.env:ro
      # Logs volume
      - feedforward-logs:/app/logs
    environment:
      - APP_DOMAIN=https://feedforward.serveur.au
      - SECRET_KEY=${SECRET_KEY}
      # Email configuration
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      # Admin account
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # LLM API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    container_name: feedforward-caddy
    networks:
      - feedforward-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/var/log/caddy
    restart: unless-stopped
    depends_on:
      - feedforward

  # Optional: Ollama for local LLM
  ollama:
    image: ollama/ollama:latest
    container_name: feedforward-ollama
    profiles: ["with-ollama"]
    networks:
      - feedforward-net
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "ollama serve & 
      sleep 5 && 
      ollama pull llama3.2 && 
      tail -f /dev/null"

networks:
  feedforward-net:
    driver: bridge

volumes:
  feedforward-data:
    driver: local
  feedforward-logs:
    driver: local
  ollama-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local
  caddy-logs:
    driver: local