# FeedForward Documentation Configuration
# This file configures Jekyll for GitHub Pages

title: FeedForward Documentation
description: AI-Powered Formative Feedback Platform - Documentation and User Guides
author: FeedForward Contributors

# GitHub Pages configuration
baseurl: "/feed-forward" # the subpath of your site, e.g. /blog
url: "https://michael-borck.github.io" # Update with your GitHub Pages URL

# Theme configuration
remote_theme: just-the-docs/just-the-docs@v0.6.2
color_scheme: light

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the top navigation
aux_links:
  "FeedForward on GitHub":
    - "https://github.com/michael-borck/feed-forward"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2024 FeedForward Contributors. Distributed under the <a href=\"https://github.com/michael-borck/feed-forward/blob/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/michael-borck/feed-forward"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Google Analytics (optional - add your tracking ID)
# ga_tracking: UA-XXXXXXXXX-X

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections for organizing content
collections:
  user-guides:
    permalink: "/:collection/:path/"
    output: true
  technical:
    permalink: "/:collection/:path/"
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      nav_order: 1
  - scope:
      path: "user-guides"
      type: "pages"
    values:
      layout: "default"
      parent: "User Guides"
  - scope:
      path: "technical"
      type: "pages"
    values:
      layout: "default"
      parent: "Technical Documentation"

# Navigation structure
nav_fold: true

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red
  tip:
    title: Tip
    color: green

# Code block configuration
code_block:
  line_numbers: false

# Markdown configuration
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from Jekyll build
exclude:
  - "*.py"
  - "*.pyc"
  - "requirements.txt"
  - "venv/"
  - "__pycache__/"
  - ".git/"
  - ".gitignore"
  - "node_modules/"
  - "package*.json"
  - ".env*"
  - "data/"
  - "*.db"